import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import "./globals.css";
import SessionIndicator from '@/_dev/components/session-indicator'
import Header from "@/components/header";
import { ThemeProvider } from "@/components/theme-provider";
import { UserProvider } from "@/contexts/user-context";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning className="dark">
      <body className={`${inter.className} dark`}>
        <UserProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
          >
            <Header />
            {children}
            <Toaster position="top-center" />
            <SessionIndicator />
          </ThemeProvider>
        </UserProvider>
      </body>
    </html>
  );
}
